# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "SKDDJ"
repo_name: "3D-arXiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 250

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Single View Reconstruction":
        filters: ["Single View Reconstruction", "Monocular 3D Reconstruction", "Single Image 3D", "Monocular Depth Estimation", "Single View 3D Generation"]
    "3D Generation":
        filters: ["3D Generation", "3D Reconstruction", "3D Shape Generation", "3D Content Creation", "3D Scene Generation"]
    "NeRF":
        filters: ["Neural Radiance Fields", "NeRF", "Novel View Synthesis", "Volume Rendering", "Implicit Neural Representations"]
    "3D Point Cloud":
        filters: ["Point Cloud", "Point Cloud Processing", "Point Cloud Generation", "Point Cloud Reconstruction", "3D Point Cloud"]
    "3D Mesh":
        filters: ["3D Mesh", "Mesh Generation", "Mesh Reconstruction", "Surface Reconstruction", "Polygon Mesh", "Triangle Mesh"]
    "Gaussian Splatting":
        filters: ["Gaussian Splatting", "3D Gaussian Splatting", "Neural Gaussian Splatting", "Point-Based Rendering"]
    "3D Scene Understanding":
        filters: ["3D Scene Understanding", "Scene Layout Estimation", "3D Scene Analysis", "Scene Geometry", "3D Scene Representation"]
    "Neural Rendering":
        filters: ["Neural Rendering", "Differentiable Rendering", "Neural Scene Representation", "View Synthesis", "Neural Graphics"]
    "Voxel":
        filters: ["Voxel", "Voxel Grid", "Volumetric Representation", "3D Voxel", "Voxel-based Methods"]
    "3D Vision-Language":
        filters: ["3D Vision Language", "3D-Aware Generation", "Text-to-3D", "3D Scene Generation from Text", "Multimodal 3D"]

